version: "3"

services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./web:/online_store/web
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on: 
      - redis
  rabbitmq:
    image: rabbitmq:3.7.8
    #command: sh -c "rabbitmq-plugins enable rabbitmq_management; rabbitmq-server"
    env_file: 
      - .env
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "7000:15672"
      - "7001:5672"
  celery:
    build: .
    command: sh -c "celery -A web worker -B"
    #command: sh -c "celery -A web flower"
    volumes:
      - ./web:/online_store/web
    env_file:
      - .env
    depends_on:
      - web
      - rabbitmq
    links: 
      - rabbitmq
  redis:
    restart: always
    image: redis:alpine
    volumes:
      - ./redis:/var/lib/redis
    expose:
      - "6379"