version: "3"

services:
  web:
    build: web
    command: sh -c "python manage.py makemigrations && python manage.py migrate"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./web:/online_store/web
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on: 
      - redis
      - database
  rabbitmq:
    image: rabbitmq:3.7.8
    #command: sh -c "rabbitmq-plugins enable rabbitmq_management; rabbitmq-server"
    env_file: 
      - .env
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "7000:15672"
      - "7001:5672"
  celery:
    build: web
    command: sh -c "celery -A web worker -B"
    #command: sh -c "celery -A web flower"
    volumes:
      - ./web:/online_store/web
    env_file:
      - .env
    depends_on:
      - web
      - rabbitmq
      - database
    links: 
      - rabbitmq
  redis:
    restart: always
    image: redis:alpine
    volumes:
      - ./redis:/var/lib/redis
    expose:
      - "6379"
  database:
    image: postgres:12
    env_file:
      - .env
    environment:
      - POSTGRES_DB:${POSTGRES_DB}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  recsys:
    build: recsys
    volumes: 
      - ./recsys:/online_store/recsys
    ports: 
      - "5000:5000"
    command: sh -c "gunicorn main:app --bind 0.0.0.0:5000"
    restart: "always"