version: "3"

services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./web:/online_store/web
    ports:
      - "8000:8000"
    env_file:
      - .env
