version: "3"

services:
  web:
    build: web
    command: sh -c "uvicorn web.asgi:application --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./web:/online_store/web
    ports:
      - "8000"
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - recsys
  rabbitmq:
    image: rabbitmq:3.7.8
    env_file:
      - .env
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "7000:15672"
      - "7001:5672"
  celery:
    build: web
    command: sh -c "celery -A web worker -B"
    volumes:
      - ./web:/online_store/web
    env_file:
      - .env
    depends_on:
      - web
      - rabbitmq
      - database
      - recsys
    links:
      - rabbitmq
  redis:
    restart: always
    image: redis:alpine
    volumes:
      - ./redis:/var/lib/redis
    expose:
      - "6379"
  database:
    image: postgres:12
    env_file:
      - .env
    environment:
      - POSTGRES_DB:${POSTGRES_DB}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  recsys:
    build: recsys
    volumes:
      - ./recsys:/online_store/recsys
    ports:
      - "5000"
    command: sh -c "gunicorn main:app --bind 0.0.0.0:5000"
    restart: "always"
  nginx:
    image: nginx:1.17.9
    ports:
      - "80:80"
    environment:
      - TZ=${TZ}
    volumes:
      - ./web/static:/online_store/web/static
      - ./web/media:/online_store/web/media
      - ./nginx/conf:/etc/nginx/
    depends_on:
      - web
